networks:
  web:
    driver: bridge

services:
  nestjs:
    build:
      context: "./nestjs"
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    networks:
      - web
  nextjs:
    build:
      context: "./nextjs"
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    networks:
      - web
    depends_on:
      - nestjs

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs 
      - nestjs
    networks:
      - web